name: CleanUp

on:
  schedule:
    - cron: "1 0 * * 0"   # <=== Change this value
  workflow_dispatch:

jobs:
  clean-up:
    runs-on: ubuntu-latest
    steps:
      - name: Delete older release
        uses: tinoji/delete-older-release-assets@v1.0.1
        with:
          keep_latest: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
