name: CleanUp

on:
  schedule:
    - cron: "1 0 * * 0"   # <=== Change this value
  workflow_dispatch:

jobs:
  clean-up:
    runs-on: ubuntu-latest
    steps:
      - name: Delete older release
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
